/**
 * @file   Font_Smooth.h
 * @brief  Smooth (anti-aliased) font support for Seeed_GFX v2.0
 *
 * Provides a standalone SmoothFont class that reads VLW-format
 * anti-aliased font data from PROGMEM and renders glyphs using
 * callback-based pixel drawing.
 *
 * Original code by Bodmer (TFT_eSPI), adapted for Seeed_GFX v2.0.
 *
 * Usage:
 * @code
 *   #include "font/Font_Smooth.h"
 *
 *   // Include a VLW font array (generated by Processing IDE)
 *   #include "myFont.h"
 *
 *   SmoothFont smoothFont;
 *
 *   void setup() {
 *       smoothFont.begin(drawPixelCallback, readPixelCallback);
 *       smoothFont.loadFont(myFontData);
 *   }
 *
 *   void loop() {
 *       smoothFont.drawChar(100, 100, 'A', TFT_WHITE, TFT_BLACK);
 *   }
 * @endcode
 */

#ifndef SEEED_GFX_FONT_SMOOTH_H
#define SEEED_GFX_FONT_SMOOTH_H

#include <Arduino.h>
#include <stdint.h>
#include <stddef.h>

#ifndef SEEED_GFX_HAS_FS
  #if defined(__has_include)
    #if __has_include(<FS.h>)
      #include <FS.h>
      #define SEEED_GFX_HAS_FS 1
    #endif
  #endif
#endif
#ifndef SEEED_GFX_HAS_FS
  #define SEEED_GFX_HAS_FS 0
#endif

// Callback types

/** Callback to draw a single pixel at (x, y) with the given color */
typedef void (*DrawPixelCallback)(int32_t x, int32_t y, uint16_t color);

/** Callback to draw a horizontal line */
typedef void (*DrawHLineCallback)(int32_t x, int32_t y, int32_t w, uint16_t color);

/** Callback to draw a filled rectangle */
typedef void (*FillRectCallback)(int32_t x, int32_t y, int32_t w, int32_t h, uint16_t color);

/** Callback to read a pixel color from the display at (x, y) */
typedef uint16_t (*ReadPixelCallback)(int32_t x, int32_t y);

// Font metrics structure

/** Holds metrics for the currently loaded smooth font */
typedef struct {
    const uint8_t* gArray;      /**< Pointer to font data array start */
    uint16_t gCount;            /**< Total number of glyphs in font */
    uint16_t yAdvance;          /**< Line advance (newline distance) */
    uint16_t spaceWidth;        /**< Width of a space character */
    int16_t  ascent;            /**< Height of top of 'd' above baseline */
    int16_t  descent;           /**< Offset to bottom of 'p' */
    uint16_t maxAscent;         /**< Maximum ascent found in font */
    uint16_t maxDescent;        /**< Maximum descent found in font */
} smoothFontMetrics;

// SmoothFont class

class SmoothFont {
public:
    SmoothFont();
    ~SmoothFont();

    // Initialization

    /**
     * @brief Set the rendering callbacks.
     * Must be called before loadFont().
     *
     * @param drawPixel  Callback to draw a single pixel
     * @param drawHLine  Callback to draw a horizontal line
     * @param fillRect   Callback to draw a filled rectangle
     * @param readPixel  Callback to read a pixel (for alpha blending with background)
     */
    void begin(DrawPixelCallback drawPixel,
               DrawHLineCallback drawHLine = nullptr,
               FillRectCallback fillRect = nullptr,
               ReadPixelCallback readPixel = nullptr);

    // Font loading

    /**
     * @brief Load a smooth font from a PROGMEM array.
     * The array must be in VLW format (generated by Processing IDE).
     *
     * @param fontData  Pointer to font data in PROGMEM
     * @return true if font loaded successfully, false on error
     */
    bool loadFont(const uint8_t* fontData);

#if SEEED_GFX_HAS_FS
    /** Load a VLW font file into owned RAM and keep it valid until unloadFont(). */
    bool loadFont(const char* path, fs::FS& fileSystem);
    bool loadFont(const String& path, fs::FS& fileSystem) {
        return loadFont(path.c_str(), fileSystem);
    }
#endif

    /**
     * @brief Unload the current font and free allocated memory.
     */
    void unloadFont();

    /**
     * @brief Check if a font is currently loaded.
     * @return true if a font is loaded
     */
    bool isLoaded() const { return _fontLoaded; }

    // Glyph rendering

    /**
     * @brief Draw a single character glyph at the specified position.
     * Uses alpha blending to render anti-aliased edges.
     *
     * @param x        X coordinate of cursor position (left of glyph)
     * @param y        Y coordinate of cursor position (baseline)
     * @param ch       Unicode character to draw
     * @param fgColor  Foreground color (text color)
     * @param bgColor  Background color
     * @return Width of the drawn character in pixels (xAdvance), or 0 if not found
     */
    uint16_t drawChar(int32_t x, int32_t y, uint16_t ch,
                      uint16_t fgColor, uint16_t bgColor);

    /**
     * @brief Draw a single character glyph with background fill.
     * Fills the area above, below, left, and right of the glyph with bgColor.
     *
     * @param x        X coordinate of cursor position
     * @param y        Y coordinate of cursor position (baseline)
     * @param ch       Unicode character to draw
     * @param fgColor  Foreground color
     * @param bgColor  Background color
     * @param fillBg   If true, fill background areas around the glyph
     * @return Width of the drawn character (xAdvance), or 0 if not found
     */
    uint16_t drawChar(int32_t x, int32_t y, uint16_t ch,
                      uint16_t fgColor, uint16_t bgColor, bool fillBg);

    // Glyph metrics

    /**
     * @brief Get the width (xAdvance) of a character.
     * @param ch  Unicode character to query
     * @return Width in pixels, or spaceWidth if character not found
     */
    uint16_t getCharWidth(uint16_t ch);

    /**
     * @brief Get the glyph bitmap width of a character.
     * @param ch  Unicode character to query
     * @return Bitmap width in pixels, or 0 if not found
     */
    uint8_t getCharBitmapWidth(uint16_t ch);

    /**
     * @brief Get the glyph bitmap height of a character.
     * @param ch  Unicode character to query
     * @return Bitmap height in pixels, or 0 if not found
     */
    uint8_t getCharBitmapHeight(uint16_t ch);

    /**
     * @brief Get the font height (line advance).
     * @return Font height in pixels (maxAscent + maxDescent)
     */
    uint16_t fontHeight() const { return _gFont.yAdvance; }

    /**
     * @brief Get the font ascent (distance from baseline to top of 'd').
     * @return Ascent in pixels
     */
    int16_t fontAscent() const { return _gFont.ascent; }

    /**
     * @brief Get the font descent (distance from baseline to bottom of 'p').
     * @return Descent in pixels
     */
    int16_t fontDescent() const { return _gFont.descent; }

    /**
     * @brief Get the maximum ascent across all glyphs.
     */
    uint16_t fontMaxAscent() const { return _gFont.maxAscent; }

    /**
     * @brief Get the maximum descent across all glyphs.
     */
    uint16_t fontMaxDescent() const { return _gFont.maxDescent; }

    /**
     * @brief Get the number of glyphs in the font.
     */
    uint16_t fontGlyphCount() const { return _gFont.gCount; }

    /**
     * @brief Get the space character width.
     */
    uint16_t fontSpaceWidth() const { return _gFont.spaceWidth; }

    /**
     * @brief Get the font metrics structure.
     */
    const smoothFontMetrics& metrics() const { return _gFont; }

    // Debug / utility

    /**
     * @brief Find the glyph index for a Unicode character.
     * @param unicode  Unicode character to find
     * @param index    Output: glyph index if found
     * @return true if found, false otherwise
     */
    bool getUnicodeIndex(uint16_t unicode, uint16_t* index);

    /**
     * @brief Display all glyphs in the font (for debugging).
     * Calls drawChar for each glyph, arranged in a grid. Pages through
     * the display, clearing the screen between pages, matching the original
     * TFT_eSPI behaviour.
     * @param screenWidth   Width of display area
     * @param screenHeight  Height of display area
     * @param fgColor       Foreground color
     * @param bgColor       Background color
     * @param pageDelay     Milliseconds to delay between pages (0 = no delay)
     */
    void showFont(uint16_t screenWidth, uint16_t screenHeight,
                  uint16_t fgColor, uint16_t bgColor,
                  uint32_t pageDelay = 0);

private:
    // Internal methods

    bool loadMetrics();
    uint32_t readInt32();
    static uint16_t alphaBlend(uint8_t alpha, uint16_t fgc, uint16_t bgc);

    // Callbacks

    DrawPixelCallback  _drawPixel  = nullptr;
    DrawHLineCallback  _drawHLine  = nullptr;
    FillRectCallback   _fillRect   = nullptr;
    ReadPixelCallback  _readPixel  = nullptr;

    // Font data

    smoothFontMetrics _gFont = { nullptr, 0, 0, 0, 0, 0, 0, 0 };
    bool _fontLoaded = false;

    const uint8_t* _fontPtr = nullptr;  /**< Current read position in font data */
    uint8_t* _ownedFontData = nullptr;  /**< Optional buffer loaded from a filesystem */
    size_t _ownedFontSize = 0;

    // Glyph metric arrays (allocated in loadMetrics)
    uint16_t* _gUnicode  = nullptr;  /**< UTF-16 code for each glyph */
    uint8_t*  _gHeight   = nullptr;  /**< Glyph bitmap height */
    uint8_t*  _gWidth    = nullptr;  /**< Glyph bitmap width */
    uint8_t*  _gxAdvance = nullptr;  /**< Cursor advance distance */
    int16_t*  _gdY       = nullptr;  /**< Offset from baseline to top of glyph */
    int8_t*   _gdX       = nullptr;  /**< Offset from cursor to left edge of glyph */
    uint32_t* _gBitmap   = nullptr;  /**< Byte offset to glyph bitmap in font data */
};

#endif // SEEED_GFX_FONT_SMOOTH_H
