#ifndef SEEED_UI_CONFIG_H
#define SEEED_UI_CONFIG_H

#ifndef SEEED_UI_EVENT_QUEUE_CAPACITY
#define SEEED_UI_EVENT_QUEUE_CAPACITY 16
#endif

#ifndef SEEED_UI_NAV_STACK_DEPTH
#define SEEED_UI_NAV_STACK_DEPTH 8
#endif

#ifndef SEEED_UI_MAX_DIRTY_RECTS
#define SEEED_UI_MAX_DIRTY_RECTS 8
#endif

#ifndef SEEED_UI_MAX_INPUT_SOURCES
#define SEEED_UI_MAX_INPUT_SOURCES 4
#endif

#ifndef SEEED_UI_MAX_BUTTONS_PER_SOURCE
#define SEEED_UI_MAX_BUTTONS_PER_SOURCE 8
#endif

#ifndef SEEED_UI_MAX_ACTION_BINDINGS
#define SEEED_UI_MAX_ACTION_BINDINGS 16
#endif

#ifndef SEEED_UI_MAX_EVENTS_PER_TICK
#define SEEED_UI_MAX_EVENTS_PER_TICK 32
#endif

#ifndef SEEED_UI_CANVAS_STACK_DEPTH
#define SEEED_UI_CANVAS_STACK_DEPTH 6
#endif

#endif
