name: Update Star History

on:
  schedule:
    - cron: "17 0 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:
  star-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Generate Star History Chart
        uses: narayann7/star-history-action@main
        with:
          repos: Seeed-Studio/Seeed_GFX2


      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add assets/star-history/

          git commit -m "Update star history chart" || exit 0

          git push
